# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6968e50769f48d440ba048f927ecc54483a078523364a9fe47c767776737ee3bed568bf6e55f1253d8c10a42f554272d186941d87891df126a66c09333a69313

test:
  secret_key_base: b30c182396ba03d158f3ced6739636600596d320e570e369ea49185d524729c1103d4b0026ab1a5b51d8af4f7e8897858b592c6ee42a1cfc39c672fceb1bed81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
